<a href="https://colab.research.google.com/github/GuilhermeBuenoMartins/sistemas-de-inferencia-fuzzy/blob/develop/Atividade_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

def straight_equation(x , y):
  theta1 = (y[1] - y[0]) / (x[1] - x[0])
  theta0 = y[0] - theta1 * x[0]
  return (theta0, theta1)

def gauss_equation(x , y):
  sigma = abs(x[1] - x[0])
  mean = x[y.index(1)]
  return (mean, sigma)

def compare(point0, point1):
  return point0[0] == point1[0] and point0[1] == point1[1]

def fuzzify(funcs, points, params, x):
  n = len(funcs)
  mu_x = np.zeros((n, 1))
  for i in range(n):
    m = funcs[i]
    point0 = points[i][0]
    pointn = points[i][m-1]
    for j in range(m):
      if x <= point0[0]:
        mu_x[i] = point0[1]
      elif  x >= pointn[0]:
        mu_x[i] = pointn[1]
      elif x > point0[0] and x < pointn[0]:
        point = points[i]
        if x >= point[j-1][0] and x < point[j][0]:
          theta0 = params[i][j-1][0]
          theta1 = params[i][j-1][1]
          mu_x[i] = theta0 + theta1 * x
  return mu_x


In [ ]:
funcs = np.array([2, 3, 3])
points = np.array([[(24,1), (27,0), (0,0), (0,0)],
                   [(24,0), (27,1), (30,0), (0,0)],
                   [(27,0), (30,1), (33,0), (0,0)]])
params = np.array([[(27/3, -1/3), (0,0), (0,0)],
                   [(-24/3, 1/3), (30/3, -1/3), (0,0)],
                   [(-27/3, 1/3), (33/3, -1/3), (0,0)]])
x = 32
fuzzify(funcs, points, params, x)

point= [33  0]


array([[0.        ],
       [0.        ],
       [0.33333333]])

array([[0.],
       [0.],
       [0.],
       [3.]])

(9.0, -0.3333333333333333)

In [ ]:
import numpy as np

def infer(var0, var1):
  mu_ = np.array([])
  for i in range(len(var0)):
    for j in range(len(var1)):
      mu_ = np.append(mu_, min(var0[i], var1[j]))
  return mu_

def infer(var0, var1, var2):
  mu_ = np.array([])
  for i in range(len(var0)):
    for j in range(len(var1)):
      for k in range(len(var2)):
        w_ = np.append(w_, min(var0[i], var1[j], var2[k]))
  return mu_

def infer(var0, var1, var2, var3):
  mu_ = np.array([])
  for i in range(len(var0)):
    for j in range(len(var1)):
      for k in range(len(var2)):
        for l in range(len(var3)):
          mu_ = np.append(mu_, min(var0[i], var1[j], var2[k], var3[l]))
  return mu_

def infer(var0, var1, var2, var4):
  mu_ = np.array([])
  for i in range(len(var0)):
    for j in range(len(var1)):
      for k in range(len(var2)):
        for l in range(len(var3)):
          for m in range(len(var4)):
            mu_ = np.append(mu_, min(var0[i], var1[j], var2[k], var3[l], var4[m]))
  return mu_

def infer(var0, var1, var2, var3, var4, var5):
  mu_ = np.array([])
  for i in range(len(var0)):
    for j in range(len(var1)):
      for k in range(len(var2)):
        for l in range(len(var3)):
          for m in range(len(var4)):
            for n in range(len(var5)):
              mu_ = np.append(mu_, min(var0[i], var1[j], var2[k], var3[l], var4[m], var5[n]))
  return mu_

def get_x(coef_, y):
  '''
  Return x value for first degree equation.

  Parameters
  ----------
  coef_ : tuple
    Tuple containing a linear and angular coefficients respectively.
    
  y: float
    Result value of sum between the linear coefficient and the product of x value and angular coefficient.

  Returns
  -------
  x
    Division result of subtraction of y and linear coefficient by angular coefficient.
  '''

  theta_0 = coef_[0]
  theta_1 = coef_[1]
  return (y - theta_0) / theta_1


In [ ]:
help(get_x)

Help on function get_x in module __main__:

get_x(coef_, y)
    Return x value for first degree equation.
    
    Parameters
    ----------
    coef_ : tuple
      Tuple containing a linear and angular coefficients respectively.
      
    y: float
      Result value of sum between the linear coefficient and the product of x value and angular coefficient.
    
    Returns
    -------
    x
      Division result of subtraction of y and linear coefficient by angular coefficient.



In [ ]:
get_x((2, 0.5), 3)

2.0

In [ ]:
arr = np.array([1, 2, 3, 2, 3, 5, 1, 2, 2])
np.where(arr == 2)


(array([1, 3, 7, 8]),)

In [27]:
def aggregation(mu_, rule_):
  '''
    Return a dictionary with the relation between linguistic term and maximum value

  Parameters
  ----------
  mu_ : numpy.ndarray
    Degree of membership for each rule
  
  rule_ : numpy.ndarray
    Output rule of linguistic term

  Returns
  -------
  agg : dict
    Dictionary of maximum values for each linguistic term
  '''

  agg = {}
  for term in np.unique(rule_):
    agg.update({term: np.max(mu_[rule_ == term])})
  return agg



In [ ]:
np.zeros((3,4)).dtype

dtype('float64')

In [ ]:
type({1: 'Vma', 2: 'Va', 3: 'Vm'})

dict

In [ ]:
help(aggregation)

Help on function aggregation in module __main__:

aggregation(mu_, rule_)
      Return a dictionary with the relation between linguistic term and maximum value
    
    Parameters
    ----------
    mu_ : numpy.ndarray
      Degree of membership for each rule
    
    rule_ : numpy.ndarray
      Output rule of linguistic term
    
    Returns
    -------
    agg : dict
      Dictionary of maximum values for each linguistic term



In [16]:
arr = np.array([1, 2, 3, 4, 2, 3, 4, 1, 2, 4, 3])

In [20]:
)

TypeError: ignored

In [12]:
agg.update({'a': 3})
agg.update({'a': 1})
agg

{'a': 1}

In [76]:
var0 = np.array([0, 1])
var1 = np.array([0.5, 0.0, 0.0, 0.0])
var2 = np.array([0.25, 0.25, 0.0, 0.0])
len(infer([var0, var1, var2]))

32

In [28]:
rule_ = np.array(['Muito pouco', 'Pouco', 'Moderado', 'Moderado', 'Pouco', 'Pouco', 'Moderado', 'Exagerado',
'Moderado', 'Moderado', 'Exagerado', 'Exagerado', 'Moderado', 'Exagerado', 'Máximo', 'Máximo'])

mu_ = np.array([0.25, 0.25, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

aggregation(mu_, rule_)



{'Exagerado': 0.0,
 'Moderado': 0.0,
 'Muito pouco': 0.25,
 'Máximo': 0.0,
 'Pouco': 0.25}

In [25]:
np.array([[[0, 1], [10, 11]], [[20, 21], [30, 31]]])

array([[[ 0,  1],
        [10, 11]],

       [[20, 21],
        [30, 31]]])

In [74]:
def get_mins(var0, var1):
  min_ = np.array([])
  for i in var0:
    for j in var1:
      x = min(i, j)
      min_ = np.append(min_, x)
  return min_

 
def infer(vars_):
  n = len(vars_)
  if (n == 2):
    return get_mins(vars_[0], vars_[1])
  else:
    var0 = vars_[0]
    var1 = infer(vars_[1:n])
    return get_mins(var0, var1)

In [46]:
var0_ = np.array([[0], [1], [3], [4], [5]])
var1_ = np.array([[0], [1], [3], [4]])
var2_ = np.array([[0], [1], [2]])

test(var0_, var1_, var2_)


(array([[0],
        [1],
        [3],
        [4],
        [5]]), array([[0],
        [1],
        [3],
        [4]]))

In [49]:
arr = []
arr.append(0)

In [50]:
arr

[0]