<a href="https://colab.research.google.com/github/GuilhermeBuenoMartins/sistemas-de-inferencia-fuzzy/blob/develop/Atividade_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [83]:
import numpy as np

def straight_equation(x , y):
  theta1 = (y[1] - y[0]) / (x[1] - x[0])
  theta0 = y[0] - theta1 * x[0]
  return (theta0, theta1)

def gauss_equation(x , y):
  sigma = abs(x[1] - x[0])
  mean = x[y.index(1)]
  return (mean, sigma)

def compare(point0, point1):
  return point0[0] == point1[0] and point0[1] == point1[1]

def fuzzify(funcs, points, params, x):
  n = len(funcs)
  mu_x = np.zeros((n, 1))
  for i in range(n):
    m = funcs[i]
    point0 = points[i][0]
    pointn = points[i][m-1]
    for j in range(m):
      if x <= point0[0]:
        mu_x[i] = point0[1]
      elif  x >= pointn[0]:
        mu_x[i] = pointn[1]
      elif x > point0[0] and x < pointn[0]:
        point = points[i]
        if x >= point[j-1][0] and x < point[j][0]:
          theta0 = params[i][j-1][0]
          theta1 = params[i][j-1][1]
          mu_x[i] = theta0 + theta1 * x
  return mu_x


In [85]:
funcs = np.array([2, 3, 3])
points = np.array([[(24,1), (27,0), (0,0), (0,0)],
                   [(24,0), (27,1), (30,0), (0,0)],
                   [(27,0), (30,1), (33,0), (0,0)]])
params = np.array([[(27/3, -1/3), (0,0), (0,0)],
                   [(-24/3, 1/3), (30/3, -1/3), (0,0)],
                   [(-27/3, 1/3), (33/3, -1/3), (0,0)]])
x = 32
fuzzify(funcs, points, params, x)

point= [33  0]


array([[0.        ],
       [0.        ],
       [0.33333333]])

In [11]:
mu_x = np.zeros((4, 1))
mu_x[3] = 3
mu_x

array([[0.],
       [0.],
       [0.],
       [3.]])

In [15]:
(27/3, -1/3)

(9.0, -0.3333333333333333)

In [20]:
points[1][3] == (3, 4)

array([False, False])