<a href="https://colab.research.google.com/github/GuilhermeBuenoMartins/sistemas-de-inferencia-fuzzy/blob/develop/Atividade_5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [46]:
import numpy as np

def straight_equation(x , y):
  theta1 = (y[1] - y[0]) / (x[1] - x[0])
  theta0 = y[0] - theta1 * x[0]
  return (theta0, theta1)

def first_degree(coef, x):
  theta_0, theta_1 = coef
  y = theta_0 + theta_1 * x
  return y

  def get_x(coef_, y):
  '''
  Return x value for first degree equation.

  Parameters
  ----------
  coef_ : tuple
    Tuple containing a linear and angular coefficients respectively.
    
  y: float
    Result value of sum between the linear coefficient and the product of x value and angular coefficient.

  Returns
  -------
  x
    Division result of subtraction of y and linear coefficient by angular coefficient.
  '''

  theta_0 = coef_[0]
  theta_1 = coef_[1]
  return (y - theta_0) / theta_1

def gauss_equation(x , y):
  sigma = abs(x[1] - x[0])
  mean = x[y.index(1)]
  return (mean, sigma)

def compare(point0, point1):
  return point0[0] == point1[0] and point0[1] == point1[1]

def fuzzify(vertices_, coefs_, x):
  '''
    Return a vector with degree of membership for each linguistic term.

    Parameters
    ----------
    vertex_ : list
      Matrix of points of linguist term vertices.

    coef_ : list
      Matrix of tuple of linear and angular coefficients respectively.

    x : float
      Values of x.

    Returns
    -------
    mu_ : numpy.ndarry
      Vector of degree of membership for each linguistic term.
  '''

  n = len(vertices_)
  mu_ = np.zeros((n,))
  for i in range(n):
    vertex_ = vertices_[i]
    m = len(vertex_)
    if (x <= vertex_[0][0]):
      mu_[i] = vertex_[0][1]
    elif (x > vertex_[-1][0]):
      mu_[i] = vertex_[-1][1]
    for j in range(1, m):
      if (x <= vertex_[j][0] and x > vertex_[j-1][0]):
        mu_[i] = first_degree(coef_[i][j-1], x)
  return mu_

def aggregation(mu_, rule_):
  '''
    Return a dictionary with the relation between linguistic term and maximum value

  Parameters
  ----------
  mu_ : numpy.ndarray
    Degree of membership for each rule
  
  rule_ : numpy.ndarray
    Output rule of linguistic term

  Returns
  -------
  agg : dict
    Dictionary of maximum values for each linguistic term
  '''

  agg = {}
  for term in np.unique(rule_):
    agg.update({term: np.max(mu_[rule_ == term])})
  return agg

def get_mins(var0, var1):
  min_ = np.array([])
  for i in var0:
    for j in var1:
      x = min(i, j)
      min_ = np.append(min_, x)
  return min_

 
def infer(vars_):
  n = len(vars_)
  if (n == 2):
    return get_mins(vars_[0], vars_[1])
  else:
    var0 = vars_[0]
    var1 = infer(vars_[1:n])
    return get_mins(var0, var1)

In [18]:
n, m = np.shape([[2, 3, 4], [5, 6, 7], [8, 9, np.nan]])
print('n = ', n)
print('m = ', m)
arr = np.array([[2, 3, 4], [5, 6, 7], [8, 9, np.nan]])
2 <= arr[2,2]

n =  3
m =  3


False

In [54]:
funcs = np.array([2, 3, 3])
vertex_ = [[(0, 1), (10, 0)],
           [(0, 0), (10, 1), (20, 0)],
           [(10, 0), (20, 1), (30,0)],
           [(20, 0), (30, 1), (40,0)]]
coef_ = [[(10/10, -1/10)],
         [(0/10, 1/10), (20/10, -1/10)],
         [(-10/10, 1/10), (30/10, -1/10)],
         [(-20/10, 1/10), (40/10, -1/10)]]
x = 21
fuzzify(vertex_, coef_, x)

array([0. , 0. , 0.9, 0.1])

In [20]:
values = (3, 5)
value_0, value_1 = values
print('Kind of values', type(values))
print('value_0', value_0)
print('value_1', value_1)

Kind of values <class 'tuple'>
value_0 3
value_1 5


In [33]:
l = [[1, 2, 3], [3, 4, 5], [3, 5, 6]]
l.index([3, 5, 6])

2

In [ ]:
help(get_x)

Help on function get_x in module __main__:

get_x(coef_, y)
    Return x value for first degree equation.
    
    Parameters
    ----------
    coef_ : tuple
      Tuple containing a linear and angular coefficients respectively.
      
    y: float
      Result value of sum between the linear coefficient and the product of x value and angular coefficient.
    
    Returns
    -------
    x
      Division result of subtraction of y and linear coefficient by angular coefficient.



In [ ]:
get_x((2, 0.5), 3)

2.0

In [ ]:
arr = np.array([1, 2, 3, 2, 3, 5, 1, 2, 2])
np.where(arr == 2)


(array([1, 3, 7, 8]),)

In [ ]:
np.zeros((3,4)).dtype

dtype('float64')

In [ ]:
type({1: 'Vma', 2: 'Va', 3: 'Vm'})

dict

In [ ]:
help(aggregation)

Help on function aggregation in module __main__:

aggregation(mu_, rule_)
      Return a dictionary with the relation between linguistic term and maximum value
    
    Parameters
    ----------
    mu_ : numpy.ndarray
      Degree of membership for each rule
    
    rule_ : numpy.ndarray
      Output rule of linguistic term
    
    Returns
    -------
    agg : dict
      Dictionary of maximum values for each linguistic term



In [16]:
arr = np.array([1, 2, 3, 4, 2, 3, 4, 1, 2, 4, 3])

In [20]:
)

TypeError: ignored

In [12]:
agg.update({'a': 3})
agg.update({'a': 1})
agg

{'a': 1}

In [76]:
var0 = np.array([0, 1])
var1 = np.array([0.5, 0.0, 0.0, 0.0])
var2 = np.array([0.25, 0.25, 0.0, 0.0])
len(infer([var0, var1, var2]))

32

In [7]:
rule_ = np.array(['Vma', 'Vma', 'Vma', 'Vma', 'Va', '-', '-','Vma','Vma',  'Vma', 'Va', 'Va', '-', '-', 'Vma','Vma', 'Vma', 'Va', 'Vm','-', '-',
 'Vma', 'Vma', 'Va', 'Va', 'Vm', '-', '-', 'Vma', 'Vma', 'Va', 'Vm', 'Vb', '-', '-', 'Vma', 'Vma', 'Va', 'Vm', '-', '-', '-',
 'Vma', 'Vma', 'Va', 'Vm', '-', '-', '-', 'Vma', 'Va', 'Vm', 'Vb', '-', '-', '-', 'Va', 'Vm', 'Vm', 'Vb', '-', '-', '-', 
'Va','Vm', 'Vb', 'Vmb', '-', '-', '-'])

mu_ = np.array([0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.25, 0.1, 0.0, 0.0, 0.0, 0.0, 0.0, 0.75, 0.1, 0.0, 0.0, 
                0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0])

aggregation(mu_, rule_)



{'-': 0.0, 'Va': 0.75, 'Vb': 0.0, 'Vm': 0.1, 'Vma': 0.0, 'Vmb': 0.0}

In [25]:
np.array([[[0, 1], [10, 11]], [[20, 21], [30, 31]]])

array([[[ 0,  1],
        [10, 11]],

       [[20, 21],
        [30, 31]]])

In [1]:
len()

70

In [46]:
var0_ = np.array([[0], [1], [3], [4], [5]])
var1_ = np.array([[0], [1], [3], [4]])
var2_ = np.array([[0], [1], [2]])

test(var0_, var1_, var2_)


(array([[0],
        [1],
        [3],
        [4],
        [5]]), array([[0],
        [1],
        [3],
        [4]]))

In [49]:
arr = []
arr.append(0)

In [50]:
arr

[0]

In [ ]:
def centroid(vertices_, coefs_, agg):
  '''
    Return a dicitonary with relation linguistic term and Centroid (C-o-M).

    Parameters
    ----------
    vertex_ : list
      Matrix of points of linguist term vertices.

    coef_ : list
      Matrix of tuple of linear and angular coefficients respectively.

    agg : dict
      Dictionary of degree of membership.

    Returns
    -------
    cof : dict
      Values of Center of Maximums.
  '''

  n = len(vertices_)
  mu_ = np.zeros((n,))
  for i in range(n):
    vertex_ = vertices_[i]
    m = len(vertex_)
    if (x <= vertex_[0][0]):
      mu_[i] = vertex_[0][1]
    elif (x > vertex_[-1][0]):
      mu_[i] = vertex_[-1][1]
    for j in range(1, m):
      if (x <= vertex_[j][0] and x > vertex_[j-1][0]):
        mu_[i] = first_degree(coef_[i][j-1], x)
  return mu_